name: Build and upload postprocessed books

on:
  - push
  - workflow_dispatch

jobs:
  collect-booklist:
    runs-on: ubuntu-latest
    outputs:
      all_books: ${{ steps.read-json.outputs.ALL_BOOKS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read from JSON
        id: read-json
        shell: bash
        run: |
          echo 'ALL_BOOKS<<EOT' >> $GITHUB_OUTPUT
          cat .github/workflows/all_books.json >> $GITHUB_OUTPUT
          echo 'EOT' >> $GITHUB_OUTPUT

  process-books:
    needs: collect-booklist
    strategy:
      matrix:
        include: ${{ fromJson(needs.collect-booklist.outputs.all_books) }}
    uses: ./.github/workflows/process_single_book.yml
    with:
      root_file: ${{ matrix.root_file }}
      working_directory: ${{ matrix.working_directory }}

  deploy-output:
    needs: process-books
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Collect artifacts and create simple index
        run: |
          mkdir -p gh-page/pdfs
          mv -v *-PDF/*.pdf gh-page/pdfs/
          mkdir -p gh-page/htmls-sp
          for SPDIR in *-HTML-SP; do
            mv -v ${SPDIR} gh-page/htmls-sp/${SPDIR%-HTML-SP}
          done
          mkdir -p gh-page/htmls-mp
          for MPDIR in *-HTML-MP; do
            mv -v ${MPDIR} gh-page/htmls-mp/${MPDIR%-HTML-MP}
          done
          mkdir -p gh-page/ebooks
          rsync -avh *-EBOOKS/* gh-page/ebooks/
          mkdir -p gh-page/epubs-calibre
          mv -v *-EPUB-CALIBRE/*.epub gh-page/epubs-calibre/
          mkdir -p gh-page/mobi
          mv -v *-MOBI-CALIBRE/*.mobi gh-page/mobi/
          mkdir -p gh-page/azw3
          mv -v *-AZW3-CALIBRE/*.azw3 gh-page/azw3/
          cp -v index.html style.css gh-page/
          cp -rv shared/images gh-page/

      - name: Generate simple sitemap.xml
        run: |
          cd gh-page
          ../tools/gen_sitemap.sh
          cd ..

      - name: Copy over robots.txt
        run: |
          cp -v robots.txt gh-page/

      - name: Touch .nojekyll
        run: |
          touch gh-page/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: endsWith(github.event.ref, '/main')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./gh-page
          force_orphan: true
